---
title: Threat and Race
author: 
- admin
date: '2020-08-28'
slug: threat-and-race
categories:
  - R
tags:
  - R Markdown
  - plot
  - ANOVA
  - time
subtitle: ''
summary: ''
authors: []
lastmod: '2020-08-28T16:00:15-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---



<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>There has always been a debate between the links of fatal police shootings and the victims. There has even been insinuations that race has an effect on the threatening nature of these individuals. That interactions with police among specific racial groups might, on average be more aggressive or carry higher risk. This topic often sparks outrage within the black and POC communities and within law enforcement.</p>
<p>I’m going to to explore this sensitive topic and try to make some inferential findings.</p>
</div>
<div id="the-data" class="section level1">
<h1>The Data</h1>
<p>The dataset can be found <a href="https://github.com/washingtonpost/data-police-shootings">here</a>.</p>
<p>We have three variables to look at: <code>attack</code>, <code>other</code>, and <code>undetermined</code>. Attack constitutes as the individual was reported to have posed immediate threat to the officer. <code>Other</code> is every other level of threat and <code>undetermined</code> is for any circumstance that through the vetting process, threat level could not be determined.
Keep in mind how the level of threat is determined, as explained in the home page.</p>
<p>Let’s look at the visualization of the raw numbers/counts. Figure 1 below shows the level of reported threat by race.</p>
<p><img src="/post/2020-08-28-threat-and-race.en_files/figure-html/unnamed-chunk-1-1.png" width="672" />
Figure 1.
<em>Amount of Fatal Police Shootings by Race since 2015</em></p>
<p>All three graphs look identical. The only visual difference is the volume of the counts. I think in this case, looking at the proportions will be more inferential.</p>
</div>
<div id="when-victims-are-threatening" class="section level1">
<h1>When Victims are Threatening</h1>
<p>I wanted to explore some general statistics of when a victim pose an immediate threat to a police officer’s life. Figure 2 depics a boxplot with the proportions of those who pose immediate threat to an officers life by race.</p>
<p><img src="/post/2020-08-28-threat-and-race.en_files/figure-html/unnamed-chunk-2-1.png" width="672" />
Figure 2.
<em>Box plot and distribution of the proportions of victims who are recorded to have posed a threat to an officer’s life by race from 2015 to current.</em></p>
<p>From 2015 to current, it is depicted through Figure 2 that the largest proportion of those who are recorded to be threatening have tended to be White, then Black, Hispanic, Not Recorded, Asian, Native and Other, respectively.</p>
<pre><code>## 
## Call:
## lm(formula = race.proportion ~ race, data = .)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.094020 -0.004781 -0.000993  0.011865  0.185885 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   0.013992   0.019169   0.730 0.470298    
## raceBlack     0.227372   0.027109   8.387 6.83e-10 ***
## raceHispanic  0.132954   0.027109   4.904 2.14e-05 ***
## raceNative   -0.001808   0.027109  -0.067 0.947208    
## raceNR        0.106430   0.027109   3.926 0.000387 ***
## raceOther    -0.005531   0.027109  -0.204 0.839508    
## raceWhite     0.442641   0.027109  16.328  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.04695 on 35 degrees of freedom
## Multiple R-squared:  0.9258, Adjusted R-squared:  0.9131 
## F-statistic: 72.76 on 6 and 35 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Display 1. <em>Simple linear regression model where <code>race</code> predicts the proportion of <code>threat_level</code>.</em></p>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)    
## race         6 0.9625  0.1604   72.76 &lt;2e-16 ***
## Residuals   35 0.0772  0.0022                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Display 2. <em>One-way ANOVA on proportion means by race</em></p>
<p><img src="/post/2020-08-28-threat-and-race.en_files/figure-html/unnamed-chunk-5-1.png" width="672" />
Figure 3. <em>Confidence intervals of the differencein mean levels of race. Via Tukey’s comparison of means.</em></p>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
##     factor levels have been ordered
## 
## Fit: aov(formula = model)
## 
## $race
##                        diff          lwr        upr     p adj
## Native-Other    0.003723252 -0.081017747 0.08846425 0.9999993
## Asian-Other     0.005531169 -0.079209831 0.09027217 0.9999930
## NR-Other        0.111960716  0.027219716 0.19670172 0.0036763
## Hispanic-Other  0.138485474  0.053744474 0.22322647 0.0002168
## Black-Other     0.232902840  0.148161841 0.31764384 0.0000000
## White-Other     0.448172295  0.363431295 0.53291329 0.0000000
## Asian-Native    0.001807917 -0.082933083 0.08654892 1.0000000
## NR-Native       0.108237464  0.023496464 0.19297846 0.0053777
## Hispanic-Native 0.134762222  0.050021222 0.21950322 0.0003255
## Black-Native    0.229179588  0.144438588 0.31392059 0.0000000
## White-Native    0.444449043  0.359708043 0.52919004 0.0000000
## NR-Asian        0.106429547  0.021688547 0.19117055 0.0064548
## Hispanic-Asian  0.132954305  0.048213305 0.21769530 0.0003962
## Black-Asian     0.227371671  0.142630672 0.31211267 0.0000000
## White-Asian     0.442641126  0.357900126 0.52738213 0.0000000
## Hispanic-NR     0.026524758 -0.058216242 0.11126576 0.9554078
## Black-NR        0.120942124  0.036201125 0.20568312 0.0014385
## White-NR        0.336211579  0.251470579 0.42095258 0.0000000
## Black-Hispanic  0.094417366  0.009676367 0.17915837 0.0208135
## White-Hispanic  0.309686821  0.224945821 0.39442782 0.0000000
## White-Black     0.215269454  0.130528455 0.30001045 0.0000000</code></pre>
<p>Display 3. <em>Table from the visualization Figure 3. provides.</em></p>
<pre><code>## Warning in boxplot.default(split(mf[[response]], mf[-response], drop = drop, :
## NAs introduced by coercion
## Warning in text.default(c(1:nlevels(r.proportion$race)),
## a$stats[nrow(a$stats), : NAs introduced by coercion</code></pre>
<p><img src="/post/2020-08-28-threat-and-race.en_files/figure-html/unnamed-chunk-7-1.png" width="672" />
Figure 4. <em>Connecting letters boxplot. Different letters result in significant differences between means</em></p>
<p>Display 1 is the output of a regression model in where we predict the proportion of the <code>attack</code> threat level via race. Our R-squared adjusted=.9131 and the p-value=2.2e-16 meaning that the regression is an appropriate model to predict the proportion of individuals that pose a threat on an officer’s life by race.</p>
<p>The regression model:
<span class="math display">\[ predicted(proportion) = 0.014 + 0.227(Black) + 0.1323(Hispanic) -0.002(Native) + 0.106(Not Recorded) - 0.006(Other) + 0.443(White) \]</span>
91.31% of the variation in proportion of those who are threatening is explained through the differences in race, but are these differences significant?</p>
<p>A One-way ANOVA (Display 2) was done to test if there is at least one mean proportion from a single race is significantly different to another. The p-value&lt;2e-16. We have enough statistical evidence to conclude at least one mean proportion of one race was significantly different than another race. A Tukey’s comparison post hoc to see what these differences are.</p>
<p>Figure 3 and Display 3 shows the output for the Tukey’s comparison of means. The output here can be hard to interpret, so a connecting letters plot was made in Figure 4. Significant differences are denoted as having different letters above each boxplot. <code>Asian</code>, <code>Native</code> and <code>Other</code> all have the same letter, so their mean proportions are not significantly different from one another, though they are significantly different than the rest of the races. <code>Hispanic</code> and the proportions of those who race is recorded as <code>Not Recorded</code> have no significant differences to each other. <code>Black</code> is significantly different than all other races. <code>White</code> is also significanly different than all other races. “a” is the smallest mean proportion while “d” is the largest mean proportion.</p>
</div>
<div id="inferential-findings-and-conclusion" class="section level1">
<h1>Inferential Findings and Conclusion</h1>
<div id="is-there-a-correlation-between-threat-level-and-race" class="section level3">
<h3>Is there a correlation between threat level and race?</h3>
<p>Doing a simple regression analysis, we find that a linear model in where race predicts the proportion of individuals that posed a threat to an officer life, is appropriate. We do not have significant evidence to say that there isn’t a correlation, in fact we have strong statistical evidence that we do. Our model also accounts for 91.31% in the variation of predicted proportion just from race alone.</p>
</div>
<div id="what-are-these-differences" class="section level3">
<h3>What are these differences?</h3>
<p>Just like how it is described in the One-way ANOVA and Tukey’s post hoc, <code>Asian</code>, <code>Native</code>, and <code>Other</code> all have predicted proportions that show no significant difference, as they are in group, “a”. <code>Hispanic</code> and <code>Not Recorded</code> also show no significant difference, group, “b”. <code>Black</code> and <code>White</code> are also in their own category, “c” and “d”, respectfully. This means that <code>White</code> has the largest mean proportion, followed by <code>Black</code>, then the group containing <code>Hispanic</code> and <code>Not Recorded</code>, followed by the group containing <code>Asian</code>, <code>Native</code>, and <code>Other</code>.</p>
</div>
<div id="conclusions" class="section level3">
<h3>Conclusions</h3>
<p>From our findings above, we have evidence to say that the mean proportion of <code>White</code> people make up the largest proportion of those who posed an immediate threat to an officer’s life in a fatal police shooting. <code>Asian</code>, <code>Native</code> and <code>Other</code> make up the smallest proportion. While we do have a correlation and a good regression model to predict the proportion based on race, I do not think it is appropriate to say that race will predict an individual’s threat level. In this case correlation does not mean causation.</p>
<p>We can find the proportion of those who pose a threat to a police officer is more likely to be White than any other race from the fact that 70% or so of the US population is White. White people also make up 40% of all the fatal police shootings It makes sense to have a higher proportion in that sense. We also have other variables to think of. Threat level is mainly based on perception and what is reported. Police can perceive an individual’s threat level based on bias and make a report that the individual did pose immediate threat to the officer’s life. Also, the data set includes social media and other means to record an individual’s theat level. So to make inferences beyond the scope of what statistical tests done is not appropriate.</p>
</div>
</div>
